"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, CalendarDays, Check, CheckCircle2, Clock3, Gem, Heart, ShieldCheck, Sparkles, Star } from "lucide-react";
import { categories } from "@/lib/data";
import { availableSlots, money, prettyDate } from "@/lib/scheduling";
import { useSalon } from "@/contexts/SalonContext";
import { useAuth } from "@/contexts/AuthContext";
import { api } from "@/lib/api";
import { Appointment } from "@/lib/types";
import { ServiceCard } from "./ServiceCard";
import { ProfessionalCard } from "./ProfessionalCard";
import { StatusBadge } from "./StatusBadge";

type Navigate=(page:string,payload?:string)=>void;

export function ClientHome({navigate}:{navigate:Navigate}){
 const {services,professionals}=useSalon();
 return <><section className="hero"><div className="hero-copy"><span className="eyebrow">SALÃO PREMIUM EM CURITIBA</span><h1>Seu momento de <em>cuidado</em><br/> começa aqui.</h1><p>Experiências de beleza criadas para valorizar quem você é, com profissionais especialistas e atendimento sem pressa.</p><div className="hero-actions"><button className="primary-button large" onClick={()=>navigate('agendar')}><CalendarDays size={19}/> Agendar meu horário</button><button className="quiet-button" onClick={()=>navigate('servicos')}>Conhecer serviços</button></div><div className="trust-row"><span><Star size={15} fill="currentColor"/> 4,9 de avaliação*</span><span><ShieldCheck size={16}/> Atendimento personalizado</span><small>*Dado demonstrativo</small></div></div><div className="hero-art" aria-label="Composição abstrata elegante do Áurea Studio"><div className="arch arch-one"><span>Á</span></div><div className="arch arch-two"><Sparkles/></div><p>BEAUTY<br/>IS A RITUAL</p></div></section><section className="section"><div className="section-heading"><div><span className="eyebrow">CURADORIA DE CUIDADOS</span><h2>Escolha como quer se sentir</h2></div><button className="text-button" onClick={()=>navigate('servicos')}>Ver todos os serviços →</button></div><div className="category-strip">{categories.map((c,i)=><button key={c} onClick={()=>navigate('servicos',c)}><span>{[<Sparkles key="a"/>,<Gem key="b"/>,<Heart key="c"/>][i%3]}</span>{c}</button>)}</div><div className="card-grid three">{services.slice(0,3).map(s=><ServiceCard key={s.id} service={s} onBook={id=>navigate('agendar',id)}/>)}</div></section><section className="dark-section"><div><span className="eyebrow light">EXPERTISE QUE ACOLHE</span><h2>Profissionais que entendem<br/> sua beleza.</h2><p>Cada atendimento começa com escuta e termina com uma experiência feita para você.</p></div><div className="professional-mini-row">{professionals.slice(0,4).map(p=><button key={p.id} onClick={()=>navigate('agendar',`pro:${p.id}`)}><span className={`avatar-md tone-${p.tone}`}>{p.initials}</span><strong>{p.name.split(' ')[0]}</strong><small>{p.specialty.split('&')[0]}</small></button>)}</div></section><section className="benefits"><div><Clock3/><strong>Seu tempo importa</strong><p>Agendamento simples e lembretes claros.</p></div><div><Heart/><strong>Cuidado individual</strong><p>Serviços pensados para suas preferências.</p></div><div><CheckCircle2/><strong>Especialistas</strong><p>Profissionais habilitados em cada técnica.</p></div></section></>
}

export function ServicesView({navigate,initialCategory}:{navigate:Navigate;initialCategory?:string}){const {services}=useSalon();const [category,setCategory]=useState(initialCategory||'Todos');const [search,setSearch]=useState('');const visible=services.filter(s=>s.active&&(category==='Todos'||s.category===category)&&s.name.toLowerCase().includes(search.toLowerCase()));return <section className="page-section"><div className="page-title"><span className="eyebrow">MENU DE SERVIÇOS</span><h1>Cuidado em cada detalhe</h1><p>Valores demonstrativos e facilmente editáveis no projeto.</p></div><div className="filter-row"><div className="chips"><button className={category==='Todos'?'active':''} onClick={()=>setCategory('Todos')}>Todos</button>{categories.map(c=><button className={category===c?'active':''} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div><input aria-label="Buscar serviços" placeholder="Buscar serviço..." value={search} onChange={e=>setSearch(e.target.value)}/></div>{visible.length?<div className="card-grid three">{visible.map(s=><ServiceCard key={s.id} service={s} onBook={id=>navigate('agendar',id)}/>)}</div>:<Empty text="Nenhum serviço encontrado."/>}</section>}

export function ProfessionalsView({navigate}:{navigate:Navigate}){const {professionals}=useSalon();return <section className="page-section"><div className="page-title"><span className="eyebrow">NOSSO TIME</span><h1>Talento, técnica e sensibilidade</h1><p>Escolha quem vai acompanhar o seu momento de cuidado.</p></div><div className="card-grid three">{professionals.filter(p=>p.active).map(p=><ProfessionalCard key={p.id} professional={p} onBook={id=>navigate('agendar',`pro:${id}`)}/>)}</div></section>}

export function BookingView({navigate,initial}:{navigate:Navigate;initial?:string}){
 const {services,professionals,blocks,appointments,setAppointments,notify}=useSalon();
 const {user}=useAuth();
 const initialService=initial?.startsWith('pro:')?'':initial||''; const initialPro=initial?.startsWith('pro:')?initial.slice(4):'';
 const [step,setStep]=useState(initialService?2:1);const [serviceId,setServiceId]=useState(initialService);const [professionalId,setProfessionalId]=useState(initialPro);const [date,setDate]=useState('');const [slot,setSlot]=useState('');const [done,setDone]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{try{const raw=sessionStorage.getItem('aurea-booking-draft');if(!raw||initial)return;const draft=JSON.parse(raw);setServiceId(draft.serviceId);setProfessionalId(draft.professionalId);setDate(draft.date);setSlot(draft.slot);setStep(5);sessionStorage.removeItem('aurea-booking-draft')}catch{}},[initial]);
 const service=services.find(s=>s.id===serviceId); const eligible=professionals.filter(p=>p.active&&p.serviceIds.includes(serviceId)); const professional=professionals.find(p=>p.id===professionalId);
 const slots=useMemo(()=>service&&professional?availableSlots(date,professional,service,appointments,blocks):[],[date,professional,service,appointments,blocks]);
 const chooseService=(id:string)=>{setServiceId(id);setProfessionalId('');setStep(2)}; const choosePro=(id:string)=>{setProfessionalId(id);setStep(3)};
 const finish=async()=>{if(!service||!professional||!date||!slot)return;if(!user){sessionStorage.setItem('aurea-booking-draft',JSON.stringify({serviceId,professionalId,date,slot}));notify('Entre como cliente para confirmar o agendamento.');navigate('login','agendar');return}setBusy(true);setError('');try{const result=await api<{appointment:Appointment}>('/appointments',{method:'POST',body:JSON.stringify({serviceId,serviceName:service.name,professionalId,professionalName:professional.name,date,time:slot,duration:service.duration,price:service.price})});setAppointments([...appointments,{...result.appointment,client:user.name,phone:user.phone}]);setDone(true);notify('Agendamento realizado com sucesso!')}catch(err){setError(err instanceof Error?err.message:'Não foi possível realizar o agendamento.')}finally{setBusy(false)}};
 if(done)return <section className="success-page"><span><Check size={32}/></span><small>AGENDAMENTO CONCLUÍDO</small><h1>Seu momento está reservado.</h1><p>Você poderá consultar, cancelar ou reagendar em “Meus horários”.</p><div className="confirmation-card"><div><small>Serviço</small><strong>{service?.name}</strong></div><div><small>Profissional</small><strong>{professional?.name}</strong></div><div><small>Data e horário</small><strong>{prettyDate(date)} às {slot}</strong></div><div><small>Valor</small><strong>{money(service?.price||0)}</strong></div></div><button className="primary-button" onClick={()=>navigate('meus-agendamentos')}>Ver meus agendamentos</button></section>;
 const labels=['Serviço','Profissional','Data','Horário','Confirmação'];
 return <section className="booking-page"><div className="booking-head"><span className="eyebrow">AGENDAMENTO ONLINE</span><h1>Reserve seu momento</h1><div className="steps">{labels.map((l,i)=><div key={l} className={step===i+1?'current':step>i+1?'complete':''}><span>{step>i+1?<Check size={14}/>:i+1}</span><small>{l}</small></div>)}</div></div><div className="booking-panel">{step>1&&<button className="back-button" onClick={()=>setStep(step-1)}><ArrowLeft size={17}/> Voltar</button>}{step===1&&<><h2>Qual cuidado você deseja?</h2><p>Selecione um serviço para continuar.</p><div className="selection-list">{services.filter(s=>s.active).map(s=><button key={s.id} onClick={()=>chooseService(s.id)}><span className="selection-icon"><Sparkles size={18}/></span><span><strong>{s.name}</strong><small>{s.category} • {s.duration} min</small></span><b>{money(s.price)}</b></button>)}</div></>}{step===2&&<><h2>Escolha seu profissional</h2><p>Mostramos apenas especialistas habilitados para {service?.name}.</p><div className="selection-list">{eligible.map(p=><button key={p.id} onClick={()=>choosePro(p.id)}><span className={`avatar-sm tone-${p.tone}`}>{p.initials}</span><span><strong>{p.name}</strong><small>{p.specialty}</small></span><b>Selecionar →</b></button>)}</div></>}{step===3&&<><h2>Escolha uma data</h2><p>A agenda respeita expediente, folgas e indisponibilidades.</p><input className="date-input" type="date" aria-label="Data do agendamento" min={new Date().toISOString().slice(0,10)} value={date} onChange={e=>{setDate(e.target.value);setStep(4)}}/></>}{step===4&&<><h2>Horários disponíveis</h2><p>{professional?.name} • {date&&prettyDate(date)}</p>{slots.length?<div className="slot-grid">{slots.map(s=><button key={s} className={slot===s?'selected':''} onClick={()=>{setSlot(s);setStep(5)}}>{s}</button>)}</div>:<Empty text="Não há horários disponíveis nesta data. Volte e escolha outro dia."/>}</>}{step===5&&<><h2>Confira os detalhes</h2><p>Revise antes de confirmar o agendamento.</p><div className="summary-list"><div><span>Serviço</span><strong>{service?.name}</strong></div><div><span>Profissional</span><strong>{professional?.name}</strong></div><div><span>Data e horário</span><strong>{prettyDate(date)} às {slot}</strong></div><div><span>Duração</span><strong>{service?.duration} minutos</strong></div><div><span>Valor</span><strong>{money(service?.price||0)}</strong></div></div>{!user&&<p className="booking-login-note">Você poderá escolher livremente; o login será solicitado apenas para confirmar.</p>}{error&&<div className="auth-error" role="alert">{error}</div>}<button className="primary-button wide" onClick={finish} disabled={busy}>{busy?'Confirmando...':'Confirmar agendamento'}</button></>}</div></section>
}

export function MyAppointments({navigate}:{navigate:Navigate}){const {services,professionals,notify}=useSalon();const [mine,setMine]=useState<Appointment[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');useEffect(()=>{api<{appointments:Appointment[]}>('/appointments/mine').then(r=>setMine(r.appointments)).catch(err=>setError(err instanceof Error?err.message:'Não foi possível carregar seus horários.')).finally(()=>setLoading(false))},[]);const upcoming=mine.filter(a=>a.date>=new Date().toISOString().slice(0,10)&&!['Cancelado','Concluído'].includes(a.status));const history=mine.filter(a=>!upcoming.includes(a));const cancel=async(id:string)=>{if(confirm('Deseja cancelar este agendamento?')){try{await api(`/appointments/${id}/cancel`,{method:'PATCH'});setMine(mine.map(a=>a.id===id?{...a,status:'Cancelado'}:a));notify('Agendamento cancelado.')}catch(err){notify(err instanceof Error?err.message:'Não foi possível cancelar.')}}};const list=(items:Appointment[])=>items.length?<div className="appointment-list">{items.map(a=>{const s=services.find(x=>x.id===a.serviceId);const p=professionals.find(x=>x.id===a.professionalId);return <article key={a.id}><div className="date-tile"><strong>{new Date(`${a.date}T12:00`).getDate()}</strong><small>{new Intl.DateTimeFormat('pt-BR',{month:'short'}).format(new Date(`${a.date}T12:00`))}</small></div><div className="appointment-main"><StatusBadge status={a.status}/><h3>{s?.name||'Serviço'}</h3><p>{p?.name||'Profissional'} • {a.time} • {s?.duration||0} min</p></div><strong>{money(s?.price||0)}</strong>{a.status!=='Cancelado'&&a.status!=='Concluído'&&<div className="appointment-actions"><button onClick={()=>navigate('agendar',a.serviceId)}>Reagendar</button><button className="danger-link" onClick={()=>cancel(a.id)}>Cancelar</button></div>}</article>})}</div>:<Empty text="Nenhum agendamento por aqui."/>;return <section className="page-section narrow"><div className="page-title align-left"><span className="eyebrow">MINHA AGENDA</span><h1>Meus horários</h1></div>{loading?<div className="empty-state"><strong>Carregando seus horários...</strong></div>:error?<div className="auth-error">{error}</div>:<><h2 className="subheading">Próximos agendamentos</h2>{list(upcoming)}<h2 className="subheading spaced">Histórico</h2>{list(history)}</>}</section>}

export function ProfileView(){const {notify}=useSalon();const {user}=useAuth();return <section className="page-section narrow"><div className="page-title align-left"><span className="eyebrow">MINHA CONTA</span><h1>Perfil e preferências</h1><p>Mantenha seus dados atualizados para facilitar o atendimento.</p></div><form className="profile-form" onSubmit={e=>{e.preventDefault();notify('Preferências salvas neste dispositivo.')}}><label>Nome completo<input defaultValue={user?.name} readOnly/></label><div className="form-grid"><label>Telefone<input defaultValue={user?.phone} readOnly/></label><label>E-mail<input type="email" defaultValue={user?.email} readOnly/></label></div><div className="form-grid"><label>Data de nascimento <small>(opcional)</small><input type="date"/></label><label>Preferência de contato<select defaultValue="WhatsApp"><option>WhatsApp</option><option>E-mail</option><option>Telefone</option></select></label></div><label>Preferências e observações<textarea placeholder="Conte como prefere ser atendida..." rows={4}/></label><button className="primary-button" type="submit">Salvar preferências</button></form></section>}

function Empty({text}:{text:string}){return <div className="empty-state"><CalendarDays/><strong>{text}</strong><span>Tente ajustar sua seleção ou escolha outra data.</span></div>}
