"use client";
import { ReactNode, useState } from "react";
import { BarChart3, CalendarDays, CalendarPlus, ChevronLeft, CircleUserRound, Clock3, Menu, Scissors, Settings, UsersRound } from "lucide-react";
import { Brand } from "./Brand";
import { AuthUser } from "@/lib/types";
const links=[['dashboard','Visão geral',BarChart3],['agenda','Agenda',CalendarDays],['agendamentos','Agendamentos',Clock3],['clientes','Clientes',UsersRound],['profissionais-admin','Profissionais',CircleUserRound],['servicos-admin','Serviços',Scissors],['configuracoes','Configurações',Settings]] as const;
export function AdminShell({page,onNavigate,onExit,user,children}:{page:string;onNavigate:(p:string)=>void;onExit:()=>void;user:AuthUser;children:ReactNode}){
 const [open,setOpen]=useState(false); const visibleLinks=user.role==='professional'?links.filter(x=>['dashboard','agenda','agendamentos'].includes(x[0])):links;const title=visibleLinks.find(x=>x[0]===page)?.[1]||'Visão geral';const initials=user.name.split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase();
 return <div className="admin-app"><aside className={open?'admin-sidebar open':'admin-sidebar'}><Brand/><nav>{visibleLinks.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>{onNavigate(id);setOpen(false)}}><Icon size={19}/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><button onClick={onExit}><ChevronLeft size={18}/> Sair da área da equipe</button><div className="admin-user"><span>{initials}</span><div><strong>{user.name}</strong><small>{user.role==='admin'?'Administradora':'Profissional'}</small></div></div></div></aside><section className="admin-content"><header className="admin-topbar"><button className="icon-button admin-menu" onClick={()=>setOpen(!open)} aria-label="Abrir menu"><Menu size={21}/></button><div><small>Áurea Studio</small><h1>{title}</h1></div><button className="primary-button" onClick={()=>onNavigate('novo-agendamento')}><CalendarPlus size={18}/> Novo agendamento</button></header><main className="admin-main">{children}</main></section>{open&&<button className="sidebar-overlay" onClick={()=>setOpen(false)} aria-label="Fechar menu"/>}</div>
}
