"use client";
import { FormEvent, ReactNode, useState } from "react";
import { ArrowLeft, Building2, Check, Eye, EyeOff, Scissors, Sparkles, UserRound } from "lucide-react";
import { Brand } from "./Brand";
import { useAuth } from "@/contexts/AuthContext";
import { Role } from "@/lib/types";

const roleOptions=[
 {id:"client" as Role,label:"Cliente",description:"Agende e acompanhe seus horários",icon:UserRound},
 {id:"professional" as Role,label:"Cabeleireira",description:"Consulte sua agenda de atendimentos",icon:Scissors},
 {id:"admin" as Role,label:"Salão",description:"Acesse a gestão completa do studio",icon:Building2},
];

export function LoginView({navigate,returnTo}:{navigate:(page:string)=>void;returnTo?:string}){
 const {login}=useAuth();const [role,setRole]=useState<Role>(returnTo==="dashboard"?"admin":"client");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{const user=await login(email,password,role);const clientDestination=['agendar','meus-agendamentos','perfil'].includes(returnTo||'')?returnTo!:'inicio';navigate(user.role==="client"?clientDestination:"dashboard")}catch(err){setError(err instanceof Error?err.message:"Não foi possível entrar.")}finally{setBusy(false)}};
 const fillDemo=()=>{if(role==="admin"){setEmail("admin@aureastudio.com.br");setPassword("Aurea@2026")}else if(role==="professional"){setEmail("ana@aureastudio.com.br");setPassword("Profissional@2026")}else{setEmail("cliente@aureastudio.com.br");setPassword("Cliente@2026")}};
 return <AuthLayout navigate={navigate}><div className="auth-heading"><span className="eyebrow">ÁREA SEGURA</span><h1>Que bom ter você aqui.</h1><p>Escolha seu tipo de acesso e entre para continuar.</p></div><div className="role-picker">{roleOptions.map(({id,label,description,icon:Icon})=><button type="button" key={id} className={role===id?"selected":""} onClick={()=>{setRole(id);setError("")}}><Icon/><span><strong>{label}</strong><small>{description}</small></span>{role===id&&<Check className="role-check"/>}</button>)}</div><form className="auth-form" onSubmit={submit}><label>E-mail<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="seu@email.com" required/></label><label>Senha<div className="password-field"><input type={show?"text":"password"} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Sua senha" required/><button type="button" onClick={()=>setShow(!show)} aria-label={show?"Ocultar senha":"Mostrar senha"}>{show?<EyeOff/>:<Eye/>}</button></div></label>{error&&<div className="auth-error" role="alert">{error}</div>}<button className="primary-button auth-submit" disabled={busy}>{busy?"Entrando...":"Entrar"}</button></form>{role==="client"&&<p className="auth-switch">Ainda não tem conta? <button onClick={()=>navigate("cadastro")}>Cadastre-se gratuitamente</button></p>}<p className="auth-security">Seus dados de acesso são protegidos e a senha é armazenada com hash seguro.</p></AuthLayout>
}

export function RegisterView({navigate}:{navigate:(page:string)=>void}){
 const {register}=useAuth();const [form,setForm]=useState({name:"",phone:"",email:"",password:"",confirm:""});const [accept,setAccept]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const change=(key:string,value:string)=>setForm({...form,[key]:value});
 const submit=async(e:FormEvent)=>{e.preventDefault();if(form.password!==form.confirm)return setError("As senhas não coincidem.");if(!accept)return setError("Aceite os termos para continuar.");setBusy(true);setError("");try{await register(form);navigate("inicio")}catch(err){setError(err instanceof Error?err.message:"Não foi possível criar sua conta.")}finally{setBusy(false)}};
 return <AuthLayout navigate={navigate}><div className="auth-heading"><span className="eyebrow">NOVO CADASTRO</span><h1>Crie sua conta de cliente.</h1><p>Leva menos de um minuto e deixa seus próximos agendamentos mais simples.</p></div><form className="auth-form" onSubmit={submit}><label>Nome completo<input value={form.name} onChange={e=>change("name",e.target.value)} autoComplete="name" required/></label><div className="auth-form-grid"><label>Telefone<input value={form.phone} onChange={e=>change("phone",e.target.value)} autoComplete="tel" placeholder="(41) 99999-9999" required/></label><label>E-mail<input type="email" value={form.email} onChange={e=>change("email",e.target.value)} autoComplete="email" required/></label></div><div className="auth-form-grid"><label>Senha<input type="password" minLength={8} value={form.password} onChange={e=>change("password",e.target.value)} autoComplete="new-password" placeholder="Mínimo de 8 caracteres" required/></label><label>Confirmar senha<input type="password" minLength={8} value={form.confirm} onChange={e=>change("confirm",e.target.value)} autoComplete="new-password" required/></label></div><label className="terms-check"><input type="checkbox" checked={accept} onChange={e=>setAccept(e.target.checked)}/><span>Li e aceito os termos de uso e a política de privacidade do salão.</span></label>{error&&<div className="auth-error" role="alert">{error}</div>}<button className="primary-button auth-submit" disabled={busy}>{busy?"Criando conta...":"Criar minha conta"}</button></form><p className="auth-switch">Já possui cadastro? <button onClick={()=>navigate("login")}>Entrar agora</button></p></AuthLayout>
}

function AuthLayout({children,navigate}:{children:ReactNode;navigate:(page:string)=>void}){
 return <main className="auth-page"><section className="auth-brand-panel"><button className="auth-back" onClick={()=>navigate("inicio")}><ArrowLeft/> Voltar para o site</button><Brand/><div className="auth-brand-copy"><Sparkles/><span>ÁUREA STUDIO</span><h2>Beleza é sentir-se bem em sua própria história.</h2><p>Agendamentos simples, cuidado personalizado e uma experiência pensada em cada detalhe.</p></div><small>Curitiba • Atendimento com hora marcada</small></section><section className="auth-content"><div className="auth-card">{children}</div></section></main>
}
